@baseUrl = http://localhost:3333
@authToken = {{SignIn.response.body.access_token}}
@squadId = 657dee04-c744-4798-8d14-c475c74c00e3
@feedbackId = b0e49be6-83f6-4e39-a20d-5b540fa8f7c6
@targetId = c28d15b0-75e0-46a4-bfd6-0eb770d023f4

###
# @name SignUp
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{   
  "email": "ale@example.com",
  "password": "12345678"
}

###

# @name SignIn
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "davi@example.com",
  "password": "12345678"
}

###

# @name CreateSquad
POST {{baseUrl}}/squad
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Squad de Desenvolvimento"
}

###

# @name JoinSquad
POST {{baseUrl}}/squad/{{squadId}}/join
Authorization: Bearer {{authToken}}

###

# @name FindSquadsByUser
GET {{baseUrl}}/squad/find-by-user
Authorization: Bearer {{authToken}}

###

# @name PostFeedback
POST {{baseUrl}}/feedback
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Feedback de Teste",
  "content": "Este é um feedback de teste",
  "squadId": "{{squadId}}",
  "targetId": "{{targetId}}"
}

###

# @name FindSentFeedbacks
GET {{baseUrl}}/feedback/sent
Authorization: Bearer {{authToken}}

###

# @name FindById
GET {{baseUrl}}/feedback/{{feedbackId}}
Authorization: Bearer {{authToken}}

###

# @name FindReceivedFeedbacks
GET {{baseUrl}}/feedback/received
Authorization: Bearer {{authToken}}

###