# src/docs/openapi.yaml
openapi: 3.0.0
info:
  title: Feedback Hub API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: Registrar com email e senha
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpBody"
      responses:
        "201":
          description: Usuário criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /auth/signin:
    post:
      summary: Entrar com email e senha
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInBody"
      responses:
        "200":
          description: Login realizado com sucesso
          headers:
            Set-Cookie:
              description: Cookie de autenticação
              schema:
                type: string
                example: "access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignInResponse"
  /auth/signin/google:
    post:
      summary: Entrar com o Login Social (Google)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SocialLoginBody"
      responses:
        "200":
          description: Login Social realizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SocialLoginResponse"
  /auth/logout:
    post:
      summary: Fazer logout
      tags:
        - Auth
      responses:
        "200":
          description: Logout realizado com sucesso
          headers:
            Set-Cookie:
              description: Cookie de autenticação removido
              schema:
                type: string
                example: "access_token=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /user/me:
    get:
      summary: Buscar usuário logado
      tags:
        - User
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Usuário logado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /email-verification/send:
    post:
      summary: Enviar email de verificação
      tags:
        - Email
      responses:
        "200":
          description: Email enviado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /email-verification/verify:
    post:
      summary: Verificar código
      tags:
        - Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyCodeBody"
      responses:
        "200":
          description: Código verificado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /squad:
    post:
      summary: Criar um novo squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSquadBody"
      responses:
        "201":
          description: Squad criado com sucesso
  /squad/find-by-user:
    get:
      summary: Buscar squads do usuário
      tags:
        - Squads
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de squads do usuário
          content:
            application/json:
              schema:
                type: object
                properties:
                  squads:
                    type: array
                    items:
                      $ref: "#/components/schemas/SquadResponse"
  /squad/{squadId}/join:
    post:
      summary: Entrar em um squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do squad
      responses:
        "200":
          description: Usuário entrou no squad com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /squad/{squadId}/users:
    get:
      summary: Buscar usuários do squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          description: ID do squad (formato UUID)
      responses:
        "200":
          description: Lista de usuários do squad
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserResponse"
        "404":
          description: Squad não encontrado
  /squad/{squadId}/update:
    put:
      summary: Atualizar um squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do squad (formato UUID)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSquadBody"
      responses:
        "204":
          description: Squad atualizado com sucesso
        "404":
          description: Squad não encontrado
        "403":
          description: Usuário não tem permissão para atualizar o squad
  /squad/{squadId}/delete:
    delete:
      summary: Deletar um squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do squad (formato UUID)
      responses:
        "204":
          description: Squad deletado com sucesso
        "404":
          description: Squad não encontrado
        "403":
          description: Usuário não tem permissão para deletar o squad

  /squad/{squadId}/dashboard:
    get:
      summary: Dashboard do squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do squad (formato UUID)
      responses:
        "200":
          description: Dashboard do squad
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DashboardResponse"
        "404":
          description: Squad não encontrado
        "403":
          description: Usuário não tem permissão para acessar o dashboard do squad

  /squad/{squadId}/feedback/received:
    get:
      summary: Buscar feedbacks recebidos pelo usuário no squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do squad (formato UUID)
      responses:
        "200":
          description: Lista de feedbacks recebidos no squad
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedbacks:
                    type: array
                    items:
                      $ref: "#/components/schemas/FeedbackResponse"
        "404":
          description: Squad não encontrado
        "403":
          description: Usuário não é membro do squad

  /squad/{squadId}/feedback/sent:
    get:
      summary: Buscar feedbacks enviados pelo usuário no squad
      tags:
        - Squads
      security:
        - cookieAuth: []
      parameters:
        - name: squadId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do squad (formato UUID)
      responses:
        "200":
          description: Lista de feedbacks enviados no squad
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedbacks:
                    type: array
                    items:
                      $ref: "#/components/schemas/FeedbackResponse"
        "404":
          description: Squad não encontrado
        "403":
          description: Usuário não é membro do squad

  /feedback:
    post:
      summary: Criar um novo feedback
      tags:
        - Feedbacks
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFeedbackBody"
      responses:
        "201":
          description: Feedback criado com sucesso
  /feedback/{id}:
    get:
      summary: Buscar feedback por ID
      tags:
        - Feedbacks
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID do feedback
      responses:
        "200":
          description: Feedback encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    $ref: "#/components/schemas/FeedbackResponse"
  /feedback/sent:
    get:
      summary: Buscar todos os feedbacks enviados pelo usuário
      tags:
        - Feedbacks
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de feedbacks enviados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FeedbackResponse"
  /feedback/received:
    get:
      summary: Buscar todos os feedbacks recebidos pelo usuário
      tags:
        - Feedbacks
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de feedbacks recebidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FeedbackResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Autenticação via Bearer Token (deprecated - use cookieAuth)
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
      description: Autenticação via Cookie HTTP-Only
  schemas:
    SignInBody:
      type: object
      description: Dados para login
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          description: Senha do usuário
    SignUpBody:
      type: object
      description: Dados para registro
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          minLength: 6
          description: Senha do usuário (mínimo 6 caracteres)
    SocialLoginBody:
      type: object
      description: Dados para login social
      required:
        - idToken
      properties:
        provider:
          type: string
          enum:
            - google
          default: google
          description: Provedor de login social
        idToken:
          type: string
          description: Token de autenticação do provedor
    VerifyCodeBody:
      type: object
      description: Dados para verificação de código
      required:
        - code
      properties:
        code:
          type: string
          minLength: 6
          maxLength: 6
          description: Código de verificação (6 caracteres)
    CreateSquadBody:
      type: object
      description: Dados para criar um squad
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          description: Nome do squad
    UpdateSquadBody:
      type: object
      description: Dados para atualizar um squad
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          description: Nome do squad
    CreateFeedbackBody:
      type: object
      description: Dados para criar um feedback
      required:
        - title
        - content
        - targetId
        - squadId
      properties:
        title:
          type: string
          minLength: 1
          description: Título do feedback
        content:
          type: string
          minLength: 1
          description: Conteúdo do feedback
        targetId:
          type: string
          format: uuid
          description: ID do usuário que receberá o feedback
        squadId:
          type: string
          format: uuid
          description: ID do squad onde o feedback será criado
    MessageResponse:
      type: object
      description: Resposta padrão para mensagens
      properties:
        message:
          type: string
          description: Mensagem da resposta
    SignInResponse:
      type: object
      description: Resposta do login com email e senha
      properties:
        message:
          type: string
          description: Mensagem de sucesso
          example: "Signed in successfully"
    SocialLoginResponse:
      type: object
      description: Resposta do login social
      properties:
        token:
          type: string
          description: Token de autenticação JWT
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    TokenResponse:
      type: object
      description: Resposta com token de autenticação (deprecated)
      properties:
        access_token:
          type: string
          description: Token de autenticação (deprecated - use cookies)
    DashboardResponse:
      type: object
      description: Resposta com dados do dashboard
      properties:
        success:
          type: boolean
          description: Indica se a operação foi bem-sucedida
          example: true
        data:
          type: object
          description: Dados do dashboard
          properties:
            summary:
              $ref: "#/components/schemas/DashboardSummaryResponse"
            chart:
              type: array
              items:
                $ref: "#/components/schemas/DashboardChartResponse"
    DashboardSummaryResponse:
      type: object
      description: Resposta com dados do sumário do dashboard
      properties:
        feedbacks_received:
          type: integer
          description: Número de feedbacks recebidos
        feedbacks_sent:
          type: integer
          description: Número de feedbacks enviados
        unique_people:
          type: integer
          description: Número de pessoas únicas que receberam feedbacks
    DashboardChartResponse:
      type: object
      description: Resposta com dados do gráfico do dashboard
      properties:
        month:
          type: string
          description: Mês do gráfico
        received:
          type: integer
          description: Número de feedbacks recebidos
        sent:
          type: integer
          description: Número de feedbacks enviados
    SquadResponse:
      type: object
      description: Resposta com dados do squad
      properties:
        id:
          type: string
          format: uuid
          description: ID do squad
        name:
          type: string
          description: Nome do squad
        created_at:
          type: string
          format: date-time
          description: Data de criação do squad
        members_count:
          type: integer
          description: Número de membros no squad
    FeedbackResponse:
      type: object
      description: Resposta com dados do feedback
      properties:
        id:
          type: string
          format: uuid
          description: ID do feedback
        title:
          type: string
          description: Título do feedback
        content:
          type: string
          description: Conteúdo do feedback
        created_at:
          type: string
          format: date-time
          description: Data de criação do feedback
        updated_at:
          type: string
          format: date-time
          description: Data da última atualização do feedback
        owner_id:
          type: string
          format: uuid
          description: ID do usuário que criou o feedback
        target_id:
          type: string
          format: uuid
          description: ID do usuário que recebeu o feedback
        squad_id:
          type: string
          format: uuid
          description: ID do squad onde o feedback foi criado
    UserResponse:
      type: object
      description: Dados do usuário
      properties:
        id:
          type: string
          format: uuid
          description: ID do usuário
        googleId:
          type: string
          nullable: true
          description: ID do Google (pode ser null)
        name:
          type: string
          nullable: true
          description: Nome do usuário
        email:
          type: string
          format: email
          description: Email do usuário
        createdAt:
          type: string
          format: date-time
          description: Data de criação da conta
