# src/docs/openapi.yaml
openapi: 3.0.0
info:
  title: Feedback Hub API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: Registrar com email e senha
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpBody"
      responses:
        "201":
          description: Usuário criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /auth/signin:
    post:
      summary: Entrar com email e senha
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInBody"
      responses:
        "200":
          description: Token emitido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
  /auth/signin/google:
    post:
      summary: Entrar com o Login Social
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SocialLoginBody"
      responses:
        "200":
          description: Login Social realizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /email-verification/send:
    post:
      summary: Enviar email de verificação
      tags:
        - Email
      responses:
        "200":
          description: Email enviado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /email-verification/verify:
    post:
      summary: Verificar código
      tags:
        - Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyCodeBody"
      responses:
        "200":
          description: Código verificado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
components:
  schemas:
    SignInBody:
      type: object
      description: Dados para login
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          description: Senha do usuário
    SignUpBody:
      type: object
      description: Dados para registro
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: string
          minLength: 6
          description: Senha do usuário (mínimo 6 caracteres)
    SocialLoginBody:
      type: object
      description: Dados para login social
      required:
        - idToken
      properties:
        provider:
          type: string
          enum:
            - google
          default: google
          description: Provedor de login social
        idToken:
          type: string
          description: Token de autenticação do provedor
    VerifyCodeBody:
      type: object
      description: Dados para verificação de código
      required:
        - code
      properties:
        code:
          type: string
          minLength: 6
          maxLength: 6
          description: Código de verificação (6 caracteres)
    MessageResponse:
      type: object
      description: Resposta padrão para mensagens
      properties:
        message:
          type: string
          description: Mensagem da resposta
    TokenResponse:
      type: object
      description: Resposta com token de autenticação
      properties:
        token:
          type: string
          description: Token de autenticação
